# Generated by Django 5.1.2 on 2024-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="rule",
            name="rule_name",
            field=models.CharField(default="Unnamed Rule", max_length=100, unique=True),
        ),
    ]
